project_name: release_hunter

builds:
    - main: ./cmd/release-hunter/main.go
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
          - arm64

checksum:
    name_template: 'checksums.txt'

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  
release:
    github:
        owner: sv222
        name: release-hunter